"""add user fields ,  and 

Revision ID: 076ab23c83e3
Revises: dfb95b9e2277
Create Date: 2017-05-28 13:54:29.888465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076ab23c83e3'
down_revision = 'dfb95b9e2277'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('real_name', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('sex', sa.SmallInteger(), nullable=True))
    op.add_column('user', sa.Column('telephone', sa.String(length=11), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'telephone')
    op.drop_column('user', 'sex')
    op.drop_column('user', 'real_name')
    # ### end Alembic commands ###
