"""add item and item comment

Revision ID: 1235ea0ae422
Revises: dfb95b9e2277
Create Date: 2017-05-29 11:27:27.109277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1235ea0ae422'
down_revision = 'dfb95b9e2277'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('images', sa.String(length=1024), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_category_id'), 'item', ['category_id'], unique=False)
    op.create_index(op.f('ix_item_user_id'), 'item', ['user_id'], unique=False)
    op.create_table('items_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_comments_item_id'), 'items_comments', ['item_id'], unique=False)
    op.create_index(op.f('ix_items_comments_user_id'), 'items_comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_comments_user_id'), table_name='items_comments')
    op.drop_index(op.f('ix_items_comments_item_id'), table_name='items_comments')
    op.drop_table('items_comments')
    op.drop_index(op.f('ix_item_user_id'), table_name='item')
    op.drop_index(op.f('ix_item_category_id'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
