"""add report model

Revision ID: 1996b2674a7c
Revises: 99f84ffbd037
Create Date: 2017-06-07 20:01:05.769162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1996b2674a7c'
down_revision = '99f84ffbd037'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plaintiff_id', sa.Integer(), nullable=False),
    sa.Column('accused_id', sa.Integer(), nullable=False),
    sa.Column('reasion', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('valid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_accused_id'), 'report', ['accused_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_accused_id'), table_name='report')
    op.drop_table('report')
    # ### end Alembic commands ###
