"""add item fields is_trade and traded_at


Revision ID: 79bea71cd460
Revises: ddbd43bdcece
Create Date: 2017-05-30 15:42:59.128149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79bea71cd460'
down_revision = 'ddbd43bdcece'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('is_trade', sa.Boolean(), nullable=False))
    op.add_column('item', sa.Column('traded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'traded_at')
    op.drop_column('item', 'is_trade')
    # ### end Alembic commands ###
