"""add item field trade_user_id

Revision ID: d6e346c89807
Revises: 5a5cdef6341a
Create Date: 2017-06-01 02:50:17.005121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e346c89807'
down_revision = '5a5cdef6341a'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('trade_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_item_trade_user_id'), 'item', ['trade_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_trade_user_id'), table_name='item')
    op.drop_column('item', 'trade_user_id')
    # ### end Alembic commands ###
